// <auto-generated />
using System;
using DocumentDetails;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentDetails.Migrations
{
    [DbContext(typeof(DocumentDetailsContext))]
    [Migration("20220813151225_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DocumentDetails.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Extension")
                        .HasColumnType("int")
                        .HasColumnName("extension");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("main_id");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("dokumentumok", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Extension = 0,
                            Source = 0,
                            Title = "Szamlak_20200112153545"
                        },
                        new
                        {
                            Id = 2,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_1"
                        },
                        new
                        {
                            Id = 3,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_2"
                        },
                        new
                        {
                            Id = 4,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_3"
                        },
                        new
                        {
                            Id = 5,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_4"
                        },
                        new
                        {
                            Id = 6,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_5"
                        },
                        new
                        {
                            Id = 7,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_6"
                        },
                        new
                        {
                            Id = 8,
                            Extension = 0,
                            ParentId = 1,
                            Source = 1,
                            Title = "Szamla_20200112153545_7"
                        },
                        new
                        {
                            Id = 9,
                            Extension = 0,
                            Source = 2,
                            Title = "Szamlak_20200115132432"
                        },
                        new
                        {
                            Id = 10,
                            Extension = 0,
                            Source = 0,
                            Title = "Szamlak_20200116135412"
                        },
                        new
                        {
                            Id = 11,
                            Extension = 0,
                            ParentId = 10,
                            Source = 1,
                            Title = "Szamla_20200116135412_1"
                        },
                        new
                        {
                            Id = 12,
                            Extension = 0,
                            ParentId = 10,
                            Source = 1,
                            Title = "Szamla_20200116135412_2"
                        },
                        new
                        {
                            Id = 13,
                            Extension = 0,
                            ParentId = 10,
                            Source = 1,
                            Title = "Szamla_20200116135412_3"
                        },
                        new
                        {
                            Id = 14,
                            Extension = 0,
                            Source = 2,
                            Title = "Jovahagyas_TesztElek_EV"
                        },
                        new
                        {
                            Id = 15,
                            Extension = 1,
                            Source = 2,
                            Title = "Jovahagyott_tetellista"
                        },
                        new
                        {
                            Id = 16,
                            Extension = 0,
                            Source = 0,
                            Title = "Szallito_FuvarBt_20200214"
                        },
                        new
                        {
                            Id = 17,
                            Extension = 0,
                            Source = 0,
                            Title = "Szallito_FuvarBt_20200216"
                        });
                });

            modelBuilder.Entity("DocumentDetails.Entities.DocumentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("dokumentum_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("esemeny_id");

                    b.Property<DateTime>("HappenedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("happened_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EventId");

                    b.ToTable("naplo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentId = 1,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DocumentId = 1,
                            EventId = 4,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DocumentId = 1,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DocumentId = 2,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DocumentId = 3,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DocumentId = 4,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DocumentId = 5,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DocumentId = 6,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DocumentId = 7,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            DocumentId = 8,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            DocumentId = 2,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            DocumentId = 2,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            DocumentId = 2,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            DocumentId = 2,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            DocumentId = 2,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            DocumentId = 2,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            DocumentId = 2,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            DocumentId = 3,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            DocumentId = 3,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            DocumentId = 3,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            DocumentId = 3,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            DocumentId = 3,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            DocumentId = 3,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            DocumentId = 3,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            DocumentId = 4,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            DocumentId = 4,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            DocumentId = 4,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            DocumentId = 4,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            DocumentId = 4,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            DocumentId = 4,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            DocumentId = 4,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            DocumentId = 5,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            DocumentId = 5,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            DocumentId = 5,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            DocumentId = 5,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            DocumentId = 5,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            DocumentId = 5,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            DocumentId = 5,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            DocumentId = 6,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            DocumentId = 6,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            DocumentId = 6,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            DocumentId = 6,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            DocumentId = 6,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            DocumentId = 6,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            DocumentId = 6,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            DocumentId = 7,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            DocumentId = 7,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            DocumentId = 7,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            DocumentId = 7,
                            EventId = 12,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            DocumentId = 7,
                            EventId = 14,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            DocumentId = 8,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            DocumentId = 8,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 39, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            DocumentId = 8,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            DocumentId = 8,
                            EventId = 12,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            DocumentId = 8,
                            EventId = 14,
                            HappenedAt = new DateTime(2020, 1, 12, 15, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            DocumentId = 9,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            DocumentId = 9,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            DocumentId = 9,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            DocumentId = 9,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            DocumentId = 9,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 27, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            DocumentId = 9,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 27, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            DocumentId = 9,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 27, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            DocumentId = 9,
                            EventId = 13,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 28, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            DocumentId = 9,
                            EventId = 14,
                            HappenedAt = new DateTime(2020, 1, 15, 13, 28, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            DocumentId = 10,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            DocumentId = 10,
                            EventId = 4,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            DocumentId = 10,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            DocumentId = 11,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            DocumentId = 12,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            DocumentId = 13,
                            EventId = 2,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            DocumentId = 11,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            DocumentId = 11,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            DocumentId = 11,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            DocumentId = 11,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            DocumentId = 11,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            DocumentId = 11,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            DocumentId = 11,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            DocumentId = 12,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            DocumentId = 12,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            DocumentId = 12,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            DocumentId = 12,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            DocumentId = 12,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            DocumentId = 12,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            DocumentId = 12,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            DocumentId = 13,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            DocumentId = 13,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            DocumentId = 13,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            DocumentId = 13,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            DocumentId = 13,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            DocumentId = 13,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            DocumentId = 13,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 13, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            DocumentId = 14,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            DocumentId = 14,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            DocumentId = 14,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            DocumentId = 14,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            DocumentId = 14,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            DocumentId = 14,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            DocumentId = 14,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            DocumentId = 14,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 26, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            DocumentId = 15,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 101,
                            DocumentId = 15,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            DocumentId = 15,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            DocumentId = 15,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 1, 16, 16, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 104,
                            DocumentId = 16,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 105,
                            DocumentId = 16,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 106,
                            DocumentId = 16,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 107,
                            DocumentId = 16,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 108,
                            DocumentId = 16,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 109,
                            DocumentId = 16,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 110,
                            DocumentId = 16,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 111,
                            DocumentId = 16,
                            EventId = 10,
                            HappenedAt = new DateTime(2020, 2, 14, 11, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 112,
                            DocumentId = 17,
                            EventId = 1,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 113,
                            DocumentId = 17,
                            EventId = 3,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 114,
                            DocumentId = 17,
                            EventId = 5,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 115,
                            DocumentId = 17,
                            EventId = 6,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 116,
                            DocumentId = 17,
                            EventId = 7,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 117,
                            DocumentId = 17,
                            EventId = 8,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 118,
                            DocumentId = 17,
                            EventId = 9,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 119,
                            DocumentId = 17,
                            EventId = 13,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 120,
                            DocumentId = 17,
                            EventId = 14,
                            HappenedAt = new DateTime(2020, 2, 16, 14, 55, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DocumentDetails.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("esemeny", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Be�rkez�s"
                        },
                        new
                        {
                            Id = 2,
                            Title = "L�trehoz�s"
                        },
                        new
                        {
                            Id = 3,
                            Title = "K�pjav�t�s"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Szepar�l�s"
                        },
                        new
                        {
                            Id = 5,
                            Title = "OCR"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Adatkinyer�s"
                        },
                        new
                        {
                            Id = 7,
                            Title = "�thelyez�s felt�lt�sre"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Adatcsomag k�sz�t�s"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Felt�lt�s"
                        },
                        new
                        {
                            Id = 10,
                            Title = "M�velet befejezve"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Mappa m�velet hiba"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Hi�nyos adatr�teg"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Sikertelen felt�lt�s"
                        },
                        new
                        {
                            Id = 14,
                            Title = "�thelyez�s sikertelen mapp�ba"
                        });
                });

            modelBuilder.Entity("DocumentDetails.Entities.DocumentLog", b =>
                {
                    b.HasOne("DocumentDetails.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentDetails.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
